### ISSUE TITLE
Remove items from setup.sh

### ISSUE THREAD

**Issue by leebaird** [vmware-labs/attack-surface-framework#1]
The README states "Prerequisites: Latest version of Kali Linux (tested on 64 bits) "

If that's the case you can remove that following items from setup.sh:
     nmap, curl, wget, and tcpdump

**Comment by m3gh** [comment]
Thanks for the suggestion leebaird, we left those packages just in case adventurous folks decide to install it in other Linux Distros, we would be interested to know about their experiences.
